version: '3.8'

services:
  web:
    image: custom-nginx
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - nginx-data:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  nginx-data:
    driver: local
    driver_opts:
      type: none
      device: /var/opt/nginx
      o: bind

